import 'package:a_one_gt/dummy_data/dummy_model.dart';

final List<String> productImages = ["assets/images/nutrition.jpg"];

final List<String> defaultGalleryImages = [
  "assets/images/nutrition.jpg",
  "assets/images/gym_products.jpg",
  "assets/images/clothing.jpg",
];

final Map<String, List<String>> productGalleryImages = {
  "Grocery": defaultGalleryImages,
  "Clothing": defaultGalleryImages,
  "Electronics": defaultGalleryImages,
  "Nutrition": defaultGalleryImages,
  "Gym Products": defaultGalleryImages,
  "Travel": defaultGalleryImages,
  "Jewellery": defaultGalleryImages,
  "Games": defaultGalleryImages,
  "E-books": defaultGalleryImages,
};

final Map<String, String> subCategoryImages = {
  for (var subList in subCategories.values)
    for (var sub in subList) sub: "assets/images/grocery.png",
};

/// CATEGORY → SUBCATEGORIES
final Map<String, List<String>> subCategories = {
  "Grocery": [
    "Spices",
    "Pulses",
    "Rice",
    "Pickles & Sauces",
    "Jam",
    "Dry Fish",
    "Biscuits",
    "Soft Drinks",
    "Milk & Yogurt",
    "Oil",
  ],

  "Clothing": [
    "T-Shirts",
    "Jeans",
    "Winter Wear",
    "Sports Wear",
    "Formal Wear",
    "Casual Wear",
  ],

  "Electronics": ["Mobiles", "Laptops", "Audio", "Wearables", "Accessories"],

  "Nutrition": [
    "Protein Supplements",
    "Vitamins",
    "Energy Drinks",
    "Workout Supplements",
    "Weight Gain",
  ],

  "Gym Products": [
    "Strength Equipment",
    "Cardio Equipment",
    "Workout Accessories",
    "Recovery Equipment",
  ],

  "Travel": ["Bags & Luggage", "Comfort", "Travel Accessories", "Organizers"],

  "Jewellery": ["Necklaces", "Rings", "Bracelets", "Earrings", "Luxury"],

  "Games": [
    "Consoles",
    "Controllers",
    "VR Gaming",
    "Gaming Furniture",
    "Accessories",
  ],

  "E-books": [
    "Programming",
    "Business",
    "Marketing",
    "Health & Fitness",
    "Travel",
    "Finance",
    "Cooking",
    "AI & Technology",
  ],
};

/// PRODUCTS
final List<Product> dummyProducts = [
  /// ================= GROCERY =================
  Product(
    id: 'g1',
    name: 'Banana',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 4,
    category: 'Grocery',
    subCategory: 'Soft Drinks',
    rating: 4.3,
    description: 'Fresh organic bananas rich in potassium.',
  ),

  Product(
    id: 'g2',
    name: 'Tomato',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 3,
    category: 'Grocery',
    subCategory: 'Spices',
    rating: 4.2,
    description: 'Juicy farm fresh tomatoes perfect for cooking.',
  ),

  Product(
    id: 'g3',
    name: 'Potato',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 2,
    category: 'Grocery',
    subCategory: 'Pulses',
    rating: 4.1,
    description: 'Premium potatoes ideal for fries and curries.',
  ),

  Product(
    id: 'g4',
    name: 'Carrot',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 3,
    category: 'Grocery',
    subCategory: 'Spices',
    rating: 4.4,
    description: 'Crunchy carrots packed with vitamin A.',
  ),

  Product(
    id: 'g5',
    name: 'Spinach',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 2,
    category: 'Grocery',
    subCategory: 'Spices',
    rating: 4.5,
    description: 'Fresh leafy spinach full of iron and nutrients.',
  ),

  Product(
    id: 'g6',
    name: 'Milk',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 5,
    category: 'Grocery',
    subCategory: 'Milk & Yogurt',
    rating: 4.6,
    description: 'Pure dairy milk rich in calcium.',
  ),

  Product(
    id: 'g7',
    name: 'Bread',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 3,
    category: 'Grocery',
    subCategory: 'Biscuits',
    rating: 4.2,
    description: 'Soft whole wheat bread freshly baked.',
  ),

  Product(
    id: 'g8',
    name: 'Eggs',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 6,
    category: 'Grocery',
    subCategory: 'Milk & Yogurt',
    rating: 4.5,
    description: 'Farm fresh eggs packed with protein.',
  ),

  Product(
    id: 'g9',
    name: 'Rice',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 12,
    category: 'Grocery',
    subCategory: 'Rice',
    rating: 4.6,
    description: 'Premium quality white rice.',
  ),

  Product(
    id: 'g10',
    name: 'Olive Oil',
    image: productImages[0],
    images: productGalleryImages['Grocery']!,
    price: 18,
    category: 'Grocery',
    subCategory: 'Oil',
    rating: 4.7,
    description: 'Extra virgin olive oil for healthy cooking.',
  ),

  /// ================= CLOTHING =================
  Product(
    id: 'cl1',
    name: 'Cotton T-Shirt',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 20,
    category: 'Clothing',
    subCategory: 'T-Shirts',
    rating: 4.4,
    description: 'Comfortable cotton t-shirt for everyday wear',
  ),

  Product(
    id: 'cl2',
    name: 'Denim Jeans',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 45,
    category: 'Clothing',
    subCategory: 'Jeans',
    rating: 4.5,
    description: 'Stylish slim-fit denim jeans',
  ),

  Product(
    id: 'cl3',
    name: 'Hoodie',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 35,
    category: 'Clothing',
    subCategory: 'Winter Wear',
    rating: 4.6,
    description: 'Warm hoodie perfect for winter',
  ),

  Product(
    id: 'cl4',
    name: 'Jacket',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 60,
    category: 'Clothing',
    subCategory: 'Winter Wear',
    rating: 4.4,
    description: 'Lightweight stylish jacket',
  ),

  Product(
    id: 'cl5',
    name: 'Shorts',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 22,
    category: 'Clothing',
    subCategory: 'Casual Wear',
    rating: 4.3,
    description: 'Comfortable casual shorts',
  ),

  Product(
    id: 'cl6',
    name: 'Sweater',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 40,
    category: 'Clothing',
    subCategory: 'Winter Wear',
    rating: 4.5,
    description: 'Warm knitted sweater',
  ),

  Product(
    id: 'cl7',
    name: 'Formal Shirt',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 30,
    category: 'Clothing',
    subCategory: 'Formal Wear',
    rating: 4.2,
    description: 'Classic formal office shirt',
  ),

  Product(
    id: 'cl8',
    name: 'Track Pants',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 28,
    category: 'Clothing',
    subCategory: 'Sports Wear',
    rating: 4.3,
    description: 'Comfortable sports track pants',
  ),

  Product(
    id: 'cl9',
    name: 'Sports Jersey',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 35,
    category: 'Clothing',
    subCategory: 'Sports Wear',
    rating: 4.4,
    description: 'Breathable sports jersey',
  ),

  Product(
    id: 'cl10',
    name: 'Winter Coat',
    image: productImages[0],
    images: productGalleryImages['Clothing']!,
    price: 80,
    category: 'Clothing',
    subCategory: 'Winter Wear',
    rating: 4.7,
    description: 'Premium winter coat',
  ),

  /// ================= ELECTRONICS =================
  Product(
    id: 'e1',
    name: 'Smartphone',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 699,
    category: 'Electronics',
    subCategory: 'Mobiles',
    rating: 4.7,
    description: 'Latest smartphone with high performance',
  ),

  Product(
    id: 'e2',
    name: 'Laptop',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 1200,
    category: 'Electronics',
    subCategory: 'Laptops',
    rating: 4.8,
    description: 'Powerful laptop for work and gaming',
  ),

  Product(
    id: 'e3',
    name: 'Wireless Earbuds',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 99,
    category: 'Electronics',
    subCategory: 'Audio',
    rating: 4.5,
    description: 'True wireless stereo earbuds',
  ),

  Product(
    id: 'e4',
    name: 'Smart Watch',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 199,
    category: 'Electronics',
    subCategory: 'Wearables',
    rating: 4.6,
    description: 'Smart watch with fitness tracking',
  ),

  Product(
    id: 'e5',
    name: 'Bluetooth Speaker',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 120,
    category: 'Electronics',
    subCategory: 'Audio',
    rating: 4.4,
    description: 'Portable bluetooth speaker',
  ),

  Product(
    id: 'e6',
    name: 'Tablet',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 400,
    category: 'Electronics',
    subCategory: 'Accessories',
    rating: 4.3,
    description: 'Lightweight tablet for entertainment',
  ),

  Product(
    id: 'e7',
    name: 'Gaming Mouse',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 70,
    category: 'Electronics',
    subCategory: 'Accessories',
    rating: 4.5,
    description: 'RGB gaming mouse',
  ),

  Product(
    id: 'e8',
    name: 'Mechanical Keyboard',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 110,
    category: 'Electronics',
    subCategory: 'Accessories',
    rating: 4.6,
    description: 'Mechanical keyboard for gamers',
  ),

  Product(
    id: 'e9',
    name: 'Monitor',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 250,
    category: 'Electronics',
    subCategory: 'Accessories',
    rating: 4.4,
    description: '24 inch HD monitor',
  ),

  Product(
    id: 'e10',
    name: 'Power Bank',
    image: productImages[0],
    images: productGalleryImages['Electronics']!,
    price: 45,
    category: 'Electronics',
    subCategory: 'Accessories',
    rating: 4.3,
    description: '10000mAh fast charging power bank',
  ),

  /// =========================
  /// 💊 Nutrition
  /// =========================
  Product(
    id: 'n1',
    name: 'Protein Powder',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 60,
    category: 'Nutrition',
    subCategory: 'Protein Supplements',
    rating: 4.7,
    description: 'Whey protein for muscle growth',
  ),

  Product(
    id: 'n2',
    name: 'Multivitamin',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 25,
    category: 'Nutrition',
    subCategory: 'Vitamins',
    rating: 4.5,
    description: 'Daily multivitamin supplement',
  ),

  Product(
    id: 'n3',
    name: 'Fish Oil',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 22,
    category: 'Nutrition',
    subCategory: 'Vitamins',
    rating: 4.4,
    description: 'Omega 3 fish oil capsules',
  ),

  Product(
    id: 'n4',
    name: 'Vitamin C',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 18,
    category: 'Nutrition',
    subCategory: 'Vitamins',
    rating: 4.3,
    description: 'Boosts immunity',
  ),

  Product(
    id: 'n5',
    name: 'Energy Drink',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 5,
    category: 'Nutrition',
    subCategory: 'Energy Drinks',
    rating: 4.2,
    description: 'Instant energy boost drink',
  ),

  Product(
    id: 'n6',
    name: 'Protein Bar',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 3,
    category: 'Nutrition',
    subCategory: 'Healthy Snacks',
    rating: 4.3,
    description: 'Healthy protein snack bar',
  ),

  Product(
    id: 'n7',
    name: 'Creatine',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 35,
    category: 'Nutrition',
    subCategory: 'Workout Supplements',
    rating: 4.6,
    description: 'Improves strength and performance',
  ),

  Product(
    id: 'n8',
    name: 'BCAA',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 28,
    category: 'Nutrition',
    subCategory: 'Workout Supplements',
    rating: 4.4,
    description: 'Muscle recovery supplement',
  ),

  Product(
    id: 'n9',
    name: 'Pre Workout',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 40,
    category: 'Nutrition',
    subCategory: 'Workout Supplements',
    rating: 4.5,
    description: 'Boost workout performance',
  ),

  Product(
    id: 'n10',
    name: 'Mass Gainer',
    image: productImages[0],
    images: productGalleryImages['Nutrition']!,
    price: 55,
    category: 'Nutrition',
    subCategory: 'Weight Gain',
    rating: 4.6,
    description: 'Weight gain supplement',
  ),

  /// =========================
  /// 🏋️ Gym Products
  /// =========================
  Product(
    id: 'gy1',
    name: 'Dumbbells',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 50,
    category: 'Gym Products',
    subCategory: 'Strength Equipment',
    rating: 4.6,
    description: 'Adjustable dumbbells',
  ),

  Product(
    id: 'gy2',
    name: 'Yoga Mat',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 20,
    category: 'Gym Products',
    subCategory: 'Workout Accessories',
    rating: 4.4,
    description: 'Comfortable yoga mat',
  ),

  Product(
    id: 'gy3',
    name: 'Skipping Rope',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 12,
    category: 'Gym Products',
    subCategory: 'Workout Accessories',
    rating: 4.3,
    description: 'High speed skipping rope',
  ),

  Product(
    id: 'gy4',
    name: 'Resistance Bands',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 18,
    category: 'Gym Products',
    subCategory: 'Workout Accessories',
    rating: 4.5,
    description: 'Workout resistance bands',
  ),

  Product(
    id: 'gy5',
    name: 'Kettlebell',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 35,
    category: 'Gym Products',
    subCategory: 'Strength Equipment',
    rating: 4.6,
    description: 'Heavy kettlebell for strength training',
  ),

  Product(
    id: 'gy6',
    name: 'Foam Roller',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 22,
    category: 'Gym Products',
    subCategory: 'Recovery Equipment',
    rating: 4.4,
    description: 'Muscle recovery foam roller',
  ),

  Product(
    id: 'gy7',
    name: 'Gym Gloves',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 15,
    category: 'Gym Products',
    subCategory: 'Workout Accessories',
    rating: 4.2,
    description: 'Protective gym gloves',
  ),

  Product(
    id: 'gy8',
    name: 'Pull Up Bar',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 40,
    category: 'Gym Products',
    subCategory: 'Strength Equipment',
    rating: 4.5,
    description: 'Door frame pull up bar',
  ),

  Product(
    id: 'gy9',
    name: 'Exercise Bike',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 300,
    category: 'Gym Products',
    subCategory: 'Cardio Equipment',
    rating: 4.7,
    description: 'Indoor exercise bike',
  ),

  Product(
    id: 'gy10',
    name: 'Treadmill',
    image: productImages[0],
    images: productGalleryImages['Gym Products']!,
    price: 900,
    category: 'Gym Products',
    subCategory: 'Cardio Equipment',
    rating: 4.8,
    description: 'Home cardio treadmill',
  ),

  /// =========================
  /// ✈️ Travel
  /// =========================
  Product(
    id: 't1',
    name: 'Travel Backpack',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 70,
    category: 'Travel',
    subCategory: 'Bags & Luggage',
    rating: 4.6,
    description: 'Large capacity travel backpack',
  ),

  Product(
    id: 't2',
    name: 'Suitcase',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 120,
    category: 'Travel',
    subCategory: 'Bags & Luggage',
    rating: 4.7,
    description: 'Hard shell travel suitcase',
  ),

  Product(
    id: 't3',
    name: 'Neck Pillow',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 15,
    category: 'Travel',
    subCategory: 'Comfort',
    rating: 4.4,
    description: 'Comfortable travel pillow',
  ),

  Product(
    id: 't4',
    name: 'Travel Adapter',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 20,
    category: 'Travel',
    subCategory: 'Travel Accessories',
    rating: 4.3,
    description: 'Universal travel adapter',
  ),

  Product(
    id: 't5',
    name: 'Passport Holder',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 12,
    category: 'Travel',
    subCategory: 'Travel Accessories',
    rating: 4.2,
    description: 'Leather passport holder',
  ),

  Product(
    id: 't6',
    name: 'Travel Bottle Set',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 10,
    category: 'Travel',
    subCategory: 'Travel Accessories',
    rating: 4.1,
    description: 'Portable travel bottle kit',
  ),

  Product(
    id: 't7',
    name: 'Luggage Tag',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 6,
    category: 'Travel',
    subCategory: 'Travel Accessories',
    rating: 4.2,
    description: 'Durable luggage tag',
  ),

  Product(
    id: 't8',
    name: 'Travel Organizer',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 14,
    category: 'Travel',
    subCategory: 'Organizers',
    rating: 4.3,
    description: 'Cable organizer pouch',
  ),

  Product(
    id: 't9',
    name: 'Portable Charger',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 35,
    category: 'Travel',
    subCategory: 'Travel Accessories',
    rating: 4.4,
    description: 'Travel power bank',
  ),

  Product(
    id: 't10',
    name: 'Sleeping Mask',
    image: productImages[0],
    images: productGalleryImages['Travel']!,
    price: 8,
    category: 'Travel',
    subCategory: 'Comfort',
    rating: 4.2,
    description: 'Comfortable sleeping mask',
  ),

  /// =========================
  /// 💍 Jewellery
  /// =========================
  Product(
    id: 'j1',
    name: 'Gold Necklace',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 450,
    category: 'Jewellery',
    subCategory: 'Necklaces',
    rating: 4.8,
    description: 'Elegant gold necklace perfect for special occasions',
  ),

  Product(
    id: 'j2',
    name: 'Diamond Ring',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 900,
    category: 'Jewellery',
    subCategory: 'Rings',
    rating: 4.9,
    description: 'Premium diamond engagement ring',
  ),

  Product(
    id: 'j3',
    name: 'Silver Bracelet',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 120,
    category: 'Jewellery',
    subCategory: 'Bracelets',
    rating: 4.6,
    description: 'Minimalist sterling silver bracelet',
  ),

  Product(
    id: 'j4',
    name: 'Pearl Earrings',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 150,
    category: 'Jewellery',
    subCategory: 'Earrings',
    rating: 4.7,
    description: 'Classic pearl earrings',
  ),

  Product(
    id: 'j5',
    name: 'Gold Bangles',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 380,
    category: 'Jewellery',
    subCategory: 'Bracelets',
    rating: 4.6,
    description: 'Traditional gold bangles',
  ),

  Product(
    id: 'j6',
    name: 'Diamond Pendant',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 500,
    category: 'Jewellery',
    subCategory: 'Luxury',
    rating: 4.8,
    description: 'Luxury diamond pendant necklace',
  ),

  Product(
    id: 'j7',
    name: 'Silver Ring',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 80,
    category: 'Jewellery',
    subCategory: 'Rings',
    rating: 4.4,
    description: 'Elegant silver ring',
  ),

  Product(
    id: 'j8',
    name: 'Gemstone Necklace',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 220,
    category: 'Jewellery',
    subCategory: 'Necklaces',
    rating: 4.5,
    description: 'Colorful gemstone necklace',
  ),

  Product(
    id: 'j9',
    name: 'Charm Bracelet',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 95,
    category: 'Jewellery',
    subCategory: 'Bracelets',
    rating: 4.3,
    description: 'Stylish charm bracelet',
  ),

  Product(
    id: 'j10',
    name: 'Platinum Ring',
    image: productImages[0],
    images: productGalleryImages['Jewellery']!,
    price: 750,
    category: 'Jewellery',
    subCategory: 'Luxury',
    rating: 4.7,
    description: 'Luxury platinum ring',
  ),

  /// =========================
  /// 🎮 Games
  /// =========================
  Product(
    id: 'gm1',
    name: 'Gaming Console',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 499,
    category: 'Games',
    subCategory: 'Consoles',
    rating: 4.8,
    description: 'Next generation gaming console',
  ),

  Product(
    id: 'gm2',
    name: 'Gaming Controller',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 70,
    category: 'Games',
    subCategory: 'Controllers',
    rating: 4.6,
    description: 'Wireless gaming controller',
  ),

  Product(
    id: 'gm3',
    name: 'VR Headset',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 350,
    category: 'Games',
    subCategory: 'VR Gaming',
    rating: 4.7,
    description: 'Immersive virtual reality headset',
  ),

  Product(
    id: 'gm4',
    name: 'Gaming Chair',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 250,
    category: 'Games',
    subCategory: 'Gaming Furniture',
    rating: 4.5,
    description: 'Ergonomic gaming chair',
  ),

  Product(
    id: 'gm5',
    name: 'Gaming Headset',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 120,
    category: 'Games',
    subCategory: 'Accessories',
    rating: 4.4,
    description: 'Surround sound gaming headset',
  ),

  Product(
    id: 'gm6',
    name: 'Racing Wheel',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 200,
    category: 'Games',
    subCategory: 'Accessories',
    rating: 4.6,
    description: 'Realistic racing simulator wheel',
  ),

  Product(
    id: 'gm7',
    name: 'Gamepad',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 45,
    category: 'Games',
    subCategory: 'Controllers',
    rating: 4.3,
    description: 'USB gamepad for PC gaming',
  ),

  Product(
    id: 'gm8',
    name: 'Arcade Stick',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 150,
    category: 'Games',
    subCategory: 'Controllers',
    rating: 4.4,
    description: 'Arcade fighting stick controller',
  ),

  Product(
    id: 'gm9',
    name: 'Gaming Keyboard',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 110,
    category: 'Games',
    subCategory: 'Accessories',
    rating: 4.6,
    description: 'RGB mechanical gaming keyboard',
  ),

  Product(
    id: 'gm10',
    name: 'Gaming Mouse',
    image: productImages[0],
    images: productGalleryImages['Games']!,
    price: 80,
    category: 'Games',
    subCategory: 'Accessories',
    rating: 4.5,
    description: 'High precision gaming mouse',
  ),

  /// =========================
  /// 📚 E-books
  /// =========================
  Product(
    id: 'eb1',
    name: 'Flutter Development Guide',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 15,
    category: 'E-books',
    subCategory: 'Programming',
    rating: 4.7,
    description: 'Complete guide to Flutter app development',
  ),

  Product(
    id: 'eb2',
    name: 'Learn Dart Programming',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 12,
    category: 'E-books',
    subCategory: 'Programming',
    rating: 4.6,
    description: 'Beginner to advanced Dart programming',
  ),

  Product(
    id: 'eb3',
    name: 'Startup Fundamentals',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 18,
    category: 'E-books',
    subCategory: 'Business',
    rating: 4.5,
    description: 'Learn how to build successful startups',
  ),

  Product(
    id: 'eb4',
    name: 'Digital Marketing Secrets',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 14,
    category: 'E-books',
    subCategory: 'Marketing',
    rating: 4.4,
    description: 'Strategies for online marketing success',
  ),

  Product(
    id: 'eb5',
    name: 'Fitness and Nutrition',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 10,
    category: 'E-books',
    subCategory: 'Health & Fitness',
    rating: 4.3,
    description: 'Guide to healthy lifestyle and nutrition',
  ),

  Product(
    id: 'eb6',
    name: 'Travel the World',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 16,
    category: 'E-books',
    subCategory: 'Travel',
    rating: 4.4,
    description: 'Top destinations around the world',
  ),

  Product(
    id: 'eb7',
    name: 'Mindfulness Meditation',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 11,
    category: 'E-books',
    subCategory: 'Health & Fitness',
    rating: 4.2,
    description: 'Guide to mindfulness and meditation',
  ),

  Product(
    id: 'eb8',
    name: 'Financial Freedom',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 13,
    category: 'E-books',
    subCategory: 'Finance',
    rating: 4.5,
    description: 'Personal finance and investing tips',
  ),

  Product(
    id: 'eb9',
    name: 'Cooking Masterclass',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 9,
    category: 'E-books',
    subCategory: 'Cooking',
    rating: 4.3,
    description: 'Learn delicious recipes from experts',
  ),

  Product(
    id: 'eb10',
    name: 'AI for Beginners',
    image: productImages[0],
    images: productGalleryImages['E-books']!,
    price: 20,
    category: 'E-books',
    subCategory: 'AI & Technology',
    rating: 4.8,
    description: 'Introduction to artificial intelligence',
  ),
];
